# This workflow will create a Pull Request when a new branch is created in github

name: Create Pull Request
description: 'Create a Pull Request for a new branch to the main branch'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - run: echo "repository = ${{ github.repository }}"
      shell: bash

    - run: echo "ref_name = ${{ github.ref_name }}"
      shell: bash

    - run: echo "commit before = ${{ github.event.before }}"
      shell: bash

    - run: echo "commit after = ${{ github.event.after }}"
      shell: bash

    - name: Check if PR already exists
      id: check-pr-exists
      run: |
        count=$(gh pr list -H ${{ github.ref_name }} -B main --repo ${{ github.repository }} --json closed --jq 'length')
        echo "$count"
        if [ "$count" -gt 0 ]
        then
          echo skipping PR creation because the PR already exists
          echo "run=false" >> "$GITHUB_OUTPUT"
        else
          echo "run=true" >> "$GITHUB_OUTPUT"
        fi
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash

    - name: Check if push is branch creation
      id: check-branch-creation
      run: |
        if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]
        then
          echo skipping PR creation because event is a branch creation
          echo "run=false" >> "$GITHUB_OUTPUT"
        else
          echo "run=true" >> "$GITHUB_OUTPUT"
        fi 
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash

    - name: Create Pull Request
      if: ${{ steps.check-pr-exists.outputs.run == 'true' && steps.check-branch-creation.outputs.run == 'true' }} 
      run: gh pr create -B main --title "PR for ${{ github.ref_name }} to main" --body "Auto created by GitHub action" --head "${{ github.ref_name }}" --repo "${{ github.repository }}"
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
